artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/nikhil-xyz/datasets/main/insurance.csv
  local_data_file: artifacts/data_ingestion/data.csv
  train_data_file: artifacts/data_ingestion/train.csv
  test_data_file: artifacts/data_ingestion/test.csv


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["data.csv", "train.csv", "test.csv"]

data_transformation:
  root_dir: artifacts/data_transformation
  train_data_path: artifacts/data_ingestion/train.csv
  test_data_path: artifacts/data_ingestion/test.csv
  preprocessor_obj_file_path : artifacts/data_transformation/preprocessor.pkl
  prepared_train_data : artifacts/data_transformation/train_arr.npy
  prepared_test_data : artifacts/data_transformation/test_arr.npy

model_trainer:
  root_dir: artifacts/model_trainer
  model_path: artifacts/model_trainer/model.pkl
  prepared_train_data : artifacts/data_transformation/train_arr.npy
  prepared_test_data : artifacts/data_transformation/test_arr.npy
  preprocessor_obj_file_path : artifacts/data_transformation/preprocessor.pkl


model_prediction:
  root_dir: artifacts/model_prediction
  preprocessor_obj_file_path : artifacts/data_transformation/preprocessor.pkl
  model_path: artifacts/model_trainer/model.pkl

  
